### ISSUE TITLE
2023.11.08 퀴즈

### ISSUE THREAD

**Issue by BJSNuruhee** [BJSNuruhee/levelup#1]
본 퀴즈는 모르면 모른다고 적으면 되고, 굳이 검색을 해서 답을 적을 필요는 없음.

다음 퀴즈에서는 적지 못한 답에 대해 다시 질문할 것이니 부담감을 갖지 않기를 바람.

##Springboot
-  java, Spirng, Springboot에 대해서 서술해보세요.

- application.properties는 무슨 역할인가요?

- 로컬, 개발, 운영에 따라 application.properties를 나눠쓰고 싶은데 어떻게 하면 될까요? ( 실제 프로젝트에도 적용 바람)

- MVC 패턴에 대해서 간단하게 설명하세요

- DTO, DAO의 개념은 무엇인가요?

- Maven은 정확히 무엇을 뜻하고 뭘하는 걸까요?

![image](https://github.com/BJSNuruhee/levelup/assets/88364980/308a9794-7072-44ac-84dc-d6b94370d6e1)
- 두 파일의 차이는 무엇일까요?

![image](https://github.com/BJSNuruhee/levelup/assets/88364980/5b940635-c20f-46c4-9f58-011796e78efc)
- pom.xml의 역할은 무엇이고 안에 구조는 어떻게 되어있을까요?

## Vue

- npm과 node의 역할은 무엇인가요

- vue-cli란 무엇인가요?

- vite란 무엇인가요?

- vite.config.js 파일의 역할은?

- package.json 파일의 역할은?

- package-lock.json  파일의 역할은?

- index.js 파일의 역할은?

- main.js 파일의 역할은?

- App.vue와 index.html의 역할에 따라 클라이언트 요청과 프론트는 어떻게 구성이 되는가에 대한 라이프사이클 설명

- npm의 역할

**Comment by yejun95** [comment]
## Springboot

✔ java, Spirng, Springboot에 대해서 서술해보세요.

 **java** 
- 프로그래밍 언어 중 하나로 객체 지향의 성격을 지니고 있다.
- 환경에 구애 받지 않고 실행이 가능한 장점을 가지며, 이는 자바의 JVM 덕분이다.
- 이 때문에 종속성이 없으므로 Managed한 언어로 불려진다.
<br>

**Spring**
- java의 프레임워크로 MVC패턴을 이용하고 있다.
- 객체 간 의존성을 최소화하여 본래 자바의 성격인 객체 지향을 위해 개발되었다. (POJO)
- Spring framework를 필수로 하며, 그 외 security 같은 다양한 기술들도 지니고 있다.
<br>

**Springboot**
- 기존 Spring으로 개발할 때, 서버를 직접 설정해줘야 하는 불편함이 존재했으며,
Spring의 기술들을 사용할 때에는 기술 간 버전 관리를 명확하게 해야 했었다.

- 이를 해결하기 위해 나온 것으로 서버가 내장되어 있으며, Spring 기술들의 버전 관리를 자동으로 해주어
빠른 개발을 가능하게 하였다.
<br>
<br>

✔ application.properties는 무슨 역할인가요?
- 프로젝트의 환경 설정이 가능하다. (서버 설정, 포트 등)
- 이를 통해 dev, prod서버의 환경 셋팅을 각각 다르게 지정할 수 있다.
<br>
<br>

✔ 로컬, 개발, 운영에 따라 application.properties를 나눠쓰고 싶은데 어떻게 하면 될까요? ( 실제 프로젝트에도 적용 바람)
- 포트 번호를 다르게 설정한다.
<br>
<br>

✔ MVC 패턴에 대해서 간단하게 설명하세요
- Model, View, Controller로 나눠지며, Controller가 클라이언트 요청을 확인하여
Model 데이터를 View로 뿌려준다.
<br>
<br>

✔ DTO, DAO의 개념은 무엇인가요?
- DTO : 데이터를 전송하는 Model 객체이며, 동적인 값이 들어가는 객체이다.
- DAO : 데이터에 접근가능한 객체
<br>
<br>

✔ Maven은 정확히 무엇을 뜻하고 뭘하는 걸까요?
- 자바에서 쓸 수 있는 유용한 기술을 모아둔 패키지이다.
- 빌드 도구로 사용한다.

✔ TestApplication.java와 TestApplicationTests.java의 차이
- 두개의 차이는 모르겠으나 TestApplicationTests.java는 Junit등과 같은 테스트를 진행하기 위해 사용한다.
<br>
<br>

✔ pom.xml의 역할은 무엇이고 안에 구조는 어떻게 되어있을까요?
- 프로젝트에서 사용되는 기술 및 버전을 관리하는 파일이다.
- xml 파일이기 때문에 태그로 관리한다.
<br>
<hr>
<br>

## Vue
✔ npm과 node의 역할은 무엇인가요
- npm : node package manager로 Maven과 동일하게 node에서 사용되는 기술을 모아둔 패키지이다.
- node : javascript를 브라우저 밖에서 실행시킬 수 있게 해준다.
<br>
<br>

✔ vue-cli란 무엇인가요?
- Single Component 기반의 vue 프로젝트를 생성하게 해주는 기능이다.
<br>
<br>

✔ vite란 무엇인가요?
- webpack과 같은 번들러로 build 시 각 파일들 (js, css, html)을 한 파일로 압축한다.
- 자바스크립트 네이티브 모듈로 작동하기 때문에 dev서버에서 빠르게 개발이 가능하다.
  - webpack과 다르게 dev서버에서 번들링을 하지 않기 때문
<br>
<br>

✔ vite.config.js 파일의 역할은?
- vite에 대한 환경 설정을 할 수 있으며, 서버에서 필요한 정보를 기입한다.
- ex) proxy, port, plugin 등
<br>
<br>

✔ package.json 파일의 역할은?
- 프로젝트에서 사용되는 기술들을 저장함과 동시에 버전 관리를 하는 파일이다. 
- 명령어를 따로 설정할 수 있다.
<br>
<br>

✔ package-lock.json 파일의 역할은?
- package.json은 개발의 자유성을 위해 버전을 폭 넓게 잡지만 package-lock.json은
버전 명시를 정확하게 하여 build 시에 사용된다.
<br>
<br>

✔ index.js 파일의 역할은?
- 폴더 마다 만들 수 있으며, 해당 폴더에서 사용되는 변수, 함수 등을 정의 해놓을 수 있다.
<br>
<br>

✔ main.js 파일의 역할은?
- vue 실행 시 제일 처음 실행되는 파일이며, 이 때문에 vue 인스턴스를 해당 파일에서 mount한다.
- 또한 전역 속성으로 사용되어질 기능들을 정의할 수 있다. ex) router
<br>
<br>

✔ App.vue와 index.html의 역할에 따라 클라이언트 요청과 프론트는 어떻게 구성이 되는가에 대한 라이프사이클 설명
- 클라이언트 요청이 들어오면 App.vue 해당 요청과 맞는 페이지를 찾는다.
- 찾은 페이지를 index.html 렌더링한다.
- 클라이언트는 index.html에 렌더링된 화면을 보게된다.
<br>
<br>

✔ npm의 역할
- 위에서 말했듯 node package manager 로써 node에서 사용가능한 다양한 기술 들을 보유하고 있는 패키지이다.
- 필요한 모듈을 npm 명령어를 통해 다운 받을 수 있다.

**Comment by yejun95** [comment]
## java에서 어떤 것에 대한 종속성이 없는가?
- 기본적으로 언어라는 것은 OS에 종속되어 해당 환경에 맞추어 사용할 수 있다.

-  C언어의 경우 컴파일 과정을 거치면서 CPU가 읽을 수 있는 코드로 변환한다.
  - 이러한 언어를 Native하다고 말한다.
  - OS와 Machine(CPU)에 의존하기 때문이다.
  - 추가로 OS는 Machine에 의존적이다. -> 당연하게도 하드웨어가 없으면 OS 설치가 불가능하기 때문
<br>

- 만약 C언어로 Linux에서만 돌아가는 프로그램을 만들었다고 해보자.
  - window 에서는 기계어로 변환되지 못함
  - Linux라는 OS에 의존해있기 때문이다. -> Native
<br>

- 하지만 java는 JVM에 의해서 OS와 CPU에 종속되지 않고 가상의 환경에서 구동된다. 

- 이 때문에 환경에 구애받지 않고 어디서든 실행이 가능한 것이다.

- 가상화 라는 것은 소프트웨어로 CPU를 구현했다고 볼 수 있다.

- 그러므로 JVM은 CPU를 구현하여 독자적으로 구동을 하니 `OS와 CPU에 종속되어있지 않다.` 라고 할 수 있다.
<br>
<hr>
<br>

- 이와 비슷한 개념으로 docker도 가상화를 통해 환경에 종속되지 않고 독자적으로 실행이 가능한 것이다.

**Comment by yejun95** [comment]
## Spring에는 MVC 패턴만 있는가?

**Comment by yejun95** [comment]
## TestApplication.java와 TestApplicationTests.java의 차이
### ✔ TestApplication.java
- `@SpringBootApplication` 어노테이션이 적용된 클래스로, 애플리케이션을 실행할 때 애플리케이션의 시작점이 된다.

- `@SpringBootApplication` 어노테이션으로 인해 스프링 부트의 자동 설정, 스프링 Bean 읽기와 생성이 모두 자동으로 설정된다.

- `@SpringBootAplication` 어노테이션이 있는 위치부터 설정을 읽어가기 때문에 이 어노테이션을 포함한 클래스는 항상 프로젝트의 최상단에 위치해야만 한다.
  - 자바 main 메서드가 포함되어 있기 때문에 어플리케이션이 시작되면 가장 먼저 실행된다.

- 아래와 같이 코드를 보면 TestApplication.java는 Springboot와 관련된 속성을 가지고 있는 어노테이션이 적용되어 있다.

```java
@SpringBootApplication
public class TestApplication {

	public static void main(String[] args) {
		SpringApplication.run(TestApplication.class, args);
	}

}
```
<br>

**- 즉, 스프링부트를 실행시키기 위한 java 파일인 것이다.**

- 내부 어노테이션

![image](https://github.com/BJSNuruhee/levelup/assets/121341413/fa11b5c1-b751-4df0-822c-9de34d0227a6)
<br>
<hr>
<br>

### ✔ TestApplicationTests.java
- 이 파일은 주로 테스트 코드를 작성하는 데 사용되는 파일이다. 

- java의 대표적인 테스트 프레임워크인 JUnit을 사용할 수 있다.

- `@SpringBootTest` 어노테이션을 사용하여 테스트 환경을 제공한다.

- 내부 어노테이션

![image](https://github.com/BJSNuruhee/levelup/assets/121341413/94c42fb7-cab3-4607-ab9f-a5ef86501808)
<br>
<hr>
<br>

- 💡 이렇게 두 파일은 각각 애플리케이션의 실행과 테스트에 관련된 역할을 담당한다.
